---
- name: ensuring pdns zone folder exists
  file: path={{ pdns_zones_dir }} state=directory
  delegate_to: localhost
  sudo: false

- name: creating pdns zones folders
  file: path={{ pdns_zones_dir }}/{{ item.zone }} state=directory
  delegate_to: localhost
  sudo: false
  with_items: pdns_records

- name: creating pdns records in zones folders
  template: src=pdns_records.j2 dest={{ pdns_zones_dir }}/{{ item.zone }}/{{ item.name }}_{{ item.type }}
  delegate_to: localhost
  sudo: false
  with_items: pdns_records
  when: item.type != "SRV"

- name: creating pdns SRV records in zones folders
  template: src=pdns_records.j2 dest={{ pdns_zones_dir }}/{{ item.zone }}/{{ item.dc_name }}{{ item.name }}_{{ item.type }}
  delegate_to: localhost
  sudo: false
  with_items: pdns_records
  when: item.type == "SRV"

- name: adding pdns records
  command: "curl -X PATCH -H 'X-API-KEY: {{ pdns_api_key }}' --data @{{ pdns_zones_dir }}/{{ item.zone }}/{{ item.name }}_{{ item.type }} http://{{ pdns_webserver }}:{{ pdns_webserver_port }}/servers/localhost/zones/{{ item.zone }}"
  delegate_to: localhost
  sudo: false
  with_items: pdns_records
  when: item.type != "SRV" and item.changed == "True"

- name: adding SRV pdns records
  command: "curl -X PATCH -H 'X-API-KEY: {{ pdns_api_key }}' --data @{{ pdns_zones_dir }}/{{ item.zone }}/{{ item.dc_name }}{{ item.name }}_{{ item.type }} http://{{ pdns_webserver }}:{{ pdns_webserver_port }}/servers/localhost/zones/{{ item.zone }}"
  delegate_to: localhost
  sudo: false
  with_items: pdns_records
  when: item.type == "SRV" and item.changed == "True"