---
# handlers file for ansible-powerdns-authoritative
- name: restart pdns
  service:
    name: "pdns"
    state: "restarted"
    sleep: 10

- name: restart mysql
  service:
    name: "mysql"
    state: "restarted"
